---

- name: Install DHCP server package
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 86400
    state: latest
    pkg:
    - isc-dhcp-server

- name: Import dhcpd configuration file
  ansible.builtin.template:
    src: isc-dhcp-server.j2
    dest: /etc/default/isc-dhcp-server
    owner: root
    group: root
    mode: "0644"
  notify:
  - Restart dhcp

- name: Import dhcpd file for pools configuration
  ansible.builtin.copy:
    src: dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: "0644"
  notify:
  - Restart dhcp

