---

- name: Install DHCP package
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 86400
    state: latest
    pkg:
    - isc-dhcp-server

#- name: Import /etc/ssh/sshd_config.d/ file
#  ansible.builtin.copy:
#    src: main.conf
#    dest: /etc/ssh/sshd_config.d/main.conf
#    owner: root
#    group: root
#    mode: "0644"
#  notify:
#  - Restart dhcp
#
#- name: "Add authorized keys"
#  ansible.posix.authorized_key:
#    user: 'rpi'
#    key: "{{ item.value }}"
#  loop: "{{ ssh_users | dict2items }}"
