---
# L'hôte localhost est dans le groupe all
# Les hôtes du groupe raspberry sont dans le groupe all

all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
  chlidren:
    raspberry:
      hosts:
        pi[1:3]:

